// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveChart(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
    return window['go']['main']['App']['SaveChart'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function GetChart(arg1) {
    return window['go']['main']['App']['GetChart'](arg1);
}

export function ListCharts() {
    return window['go']['main']['App']['ListCharts']();
}

export function DeleteChart(arg1) {
    return window['go']['main']['App']['DeleteChart'](arg1);
}

export function ExportChartsJSON() {
    return window['go']['main']['App']['ExportChartsJSON']();
}

export function SaveFileDialog(arg1) {
    return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function WriteFile(arg1, arg2) {
    return window['go']['main']['App']['WriteFile'](arg1, arg2);
}

export function CopyToClipboard(arg1) {
    return window['go']['main']['App']['CopyToClipboard'](arg1);
}
