// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveChart(arg1: string, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: string, arg9: string): Promise<number>;

export function GetChart(arg1: number): Promise<any>;

export function ListCharts(): Promise<any[]>;

export function DeleteChart(arg1: number): Promise<void>;

export function ExportChartsJSON(): Promise<string>;

export function SaveFileDialog(arg1: string): Promise<string>;

export function WriteFile(arg1: string, arg2: string): Promise<void>;

export function CopyToClipboard(arg1: string): Promise<void>;
